version: "3.9"

services:
  api:
    build: ./api
    container_name: kondor-api
    restart: unless-stopped
    ports:
      - "3333:3333"
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis

  front:
    build: ./front
    container_name: kondor-front
    restart: unless-stopped
    ports:
      - "80:80"

  db:
    image: postgres:15
    container_name: kondor-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: kondor
      POSTGRES_PASSWORD: kondor
      POSTGRES_DB: kondor
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kondor-redis
    restart: unless-stopped

volumes:
  pgdata:

